kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "strfry.fullname" . }}
#   namespace: default
  labels:
    {{- include "strfry.labels" . | nindent 4 }}
data:
  strfry.conf: |
    {{ .Values.strfryconf | nindent 4 }}